#!/usr/bin/python3
from tinyscript import *


__script__    = "BotsScheduler"
__author__    = "Alexandre D'Hondt"
__version__   = "1.2.0"
__copyright__ = "A. D'Hondt"
__license__   = "agpl-3.0"
__reference__ = "https://github.com/Nextdoor/ndscheduler"
__source__    = "https://github.com/dhondta/bots-scheduler"
__doc__ = """
This tool is a launcher for the Nextdoor Scheduler with a set of jobs based on robots made with PyBots
 (https://github.com/dhondta/python-pybots).
Moreover, it provides authentication through the use of an integrated reverse proxy.
"""


BANNER_FONT   = "smkeyboard"
DB_NDS_BASE   = "ndscheduler.core.datastore.providers.sqlite.Datastore"
DB_SQLITE_DEF = "datastore.db"
DEFAULT_USERS = ["administrator:change-this"]
LOG_FORMAT    = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
STATIC_PATH   = "static"
VENV_NAME     = ".venv"
VENV_REQS     = ["passlib", "mitmproxy", "ndscheduler==0.3.0", "pybots"]


def at_exit():
    if "static_path" in globals() and isinstance(static_path, ts.MirrorPath):
        static_path.unmirror()


if __name__ == "__main__":
    sparsers = parser.add_subparsers(dest="command", help="command to be executed")
    # run command arguments
    run = sparsers.add_parser("run", help="run the server")
    # 1. base settings
    net = run.add_argument_group("base options")
    net.add_argument("--debug", action="store_true", help="run the server in debug mode")
    net.add_argument("-j", "--jobs", action="append", default=["jobs"], help="folder with jobs to be imported")
    net.add_argument("-d", "--data-dir", default="data", help="folder with the data files to be used")
    net.add_argument("-l", "--local", action="store_true", help="force running the server locally")
    net.add_argument("-p", "--port", type=ts.port_number, default=8888, help="server's port number",
                     note="this will be the listening port of the proxy, this of the scheduler will be port+1")
    # 2. notification settings
    notify = run.add_argument_group("notification options")
    notify.add_argument("--smtp-config", default="conf/smtp.ini", type=ts.file_exists,
                        help="SMTP INI configuration file")
    notify.add_argument("--mail-profile", nargs="*", help="SMTP profile to be selected from the configuration file")
    # 3. database settings
    db = run.add_argument_group("database options")
    db.add_argument("--dbms", default="sqlite", choices=["sqlite", "postgresql", "mysql"],
                    help="database management system")
    db.add_argument("--db-config", default="conf/db.ini", type=ts.file_exists, help="database INI configuration file")
    db.add_argument("--executions-table", default="scheduler_executions", help="executions table name")
    db.add_argument("--jobs-table", default="scheduler_jobs", help="jobs table name")
    db.add_argument("--files-table", default="scheduler_files", help="data files table name")
    db.add_argument("--logs-table", default="scheduler_jobauditlogs", help="logs table name")
    # 4. APScheduler settings
    aps = run.add_argument_group("APScheduler options")
    aps.add_argument("--job-coalesce", dest="job_coal", action="store_false",
                     help="Coalesce missed executions of a job")
    aps.add_argument("--job-max-instances", dest="job_max", type=ts.pos_int, default=3,
                     help="Maximum number of concurrently executing instances of a job")
    aps.add_argument("--job-misfire", dest="job_misfire", default=3600, help="Job misfire grace time in seconds")
    aps.add_argument("--threadpool-size", dest="tp_size", type=ts.pos_int, default=2, help="Threadpool size")
    aps.add_argument("--timezone", default="UTC", help="server's timezone")
    # 5. Tornado settings
    tornado = run.add_argument_group("Tornado options")
    tornado.add_argument("--max-workers", dest="tworkers", type=ts.pos_int, default=8, help="Maximum number of workers")
    # 6. proxy settings
    proxy = run.add_argument_group("Mitmproxy options")
    proxy.add_argument("--certificate", type=ts.file_exists, help="TLS private certificate file",
                       note="if None, the default certificate of mitmproxy is used")
    proxy.add_argument("--htpasswd", type=ts.file_exists, help="authentication file",
                       note="if None, .htpasswd is automatically created with the DEFAULT_USERS")
    # maintenance commands' arguments
    sparsers.add_parser("clean", help="remove server's virtual environment")
    initialize(noargs_action="help")
    logging.renameLogger("main", "bots_scheduler")
    logging.setLoggers("apscheduler.executors.default", "mitmproxy.reverse.proxy", "ndscheduler.core.scheduler_manager",
                       "ndscheduler.core.scheduler.base", "ndscheduler.job", "ndscheduler.server.server",
                       "numexpr.utils", "tornado.access", "tornado.application")
    # complete args namespace with additional settings from the constants above
    args.db_nds_base   = DB_NDS_BASE
    args.default_users = DEFAULT_USERS
    args.static_path   = STATIC_PATH
    if args.command == "run":
        logger.info("Setting up the virtual environment...")
        os.environ['NDSCHEDULER_SETTINGS_MODULE'] = "ndscheduler.default_settings"
        with VirtualEnv(".venv", VENV_REQS) as venv:
            from core import base, run_proxy, run_server
            from ndscheduler import settings
            base._load_mail_config(args.smtp_config, *args.mail_profile)
            sys.modules['botscheduler'] = base
            logger.info("Starting the authentication proxy...")
            if not args.local:
                p = run_proxy(args)
            logger.info("Starting the scheduling server...")
            static_path = ts.MirrorPath(args.static_path, settings.STATIC_DIR_PATH)
            run_server(args)
            if not args.local:
                p.join(5)
    else:
        if os.path.isfile(DB_SQLITE_DEF):
            os.remove(DB_SQLITE_DEF)
        if os.path.isdir(VENV_NAME):
            shutil.rmtree(VENV_NAME)
        logger.info("DONE")

